### PR TITLE
Ability to turn off strict mode for compiling hb template

### PR DESCRIPTION
**Pull request by RajivSah**
Turn of strict complie of hb template by
```
handlebars-hot-reload -t <templatePath>  -j <dataPath> -m false
```

### CODE REVIEW

**Comment by RajivSah** [comment]
@tolgaerdonmez Would you please review this.

**Review by tolgaerdonmez — APPROVED** [review]
Thanks for the pr, everythings ok mergin'

**Comment by RajivSah** [comment]
@tolgaerdonmez Could you publish a new version with the new changes? Thanks

**Comment by tolgaerdonmez** [comment]
just did!

**Comment by RajivSah** [comment]
@tolgaerdonmez seems like the package was published with out building. Would you be able to fix that, please?
image

**Comment by tolgaerdonmez** [comment]
I think I fixed it :DD

**Pull request merged**
